{
 "title": "Weather data",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ruuvitagName", "query": "SELECT name FROM ruuvitag" },
   {
    "name": "ruuvitagID",
    "query": "SELECT id FROM ruuvitag WHERE name='$ruuvitagName'"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  temperature\nFROM measurements\nWHERE\n  $__timeFilter(\"time\") AND\n  ruuvitag_id = '$ruuvitagID'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  humidity\nFROM measurements\nWHERE\n  $__timeFilter(\"time\") AND\n  ruuvitag_id = '$ruuvitagID'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Air pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  pressure\nFROM measurements\nWHERE\n  $__timeFilter(\"time\") AND\n  ruuvitag_id = '$ruuvitagID'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Battery voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  battery_voltage\nFROM measurements\nWHERE\n  $__timeFilter(\"time\") AND\n  ruuvitag_id = '$ruuvitagID'\nORDER BY 1"
    }
   ]
  }
 ]
}